### ISSUE TITLE
환경변수 관련한 이슈입니다

### ISSUE THREAD

**Issue by yoonhe** [CodeSoom/project-react-3-yoonhe#42]
현재 `ci` 설정을 아래와같이 `env` 설정을 해주게되면 `process.env.[환경변수]` 이런식의 변수에 접근이 가능할거라고 예상했습니다..
```yml
- name: Install and Build 🔧 
        run: |
          npm install
          npm run build
        env:
          API_KEY : ${{ secrets.API_KEY }}
          AUTH_DOMAIN : ${{ secrets.AUTH_DOMAIN }}
          PROJECT_ID : ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET : ${{ secrets.STORAGE_BUCKET }}
          MESSAGING_SENDER_ID : ${{ secrets.MESSAGING_SENDER_ID }}
          APP_ID : ${{ secrets.APP_ID }}
          MEASUREMENT_ID : ${{ secrets.MEASUREMENT_ID }}
```

하지만 `process.env.[환경변수]` 값이 `undefined`가 나왔습니다.

그래서 아래와같이 웹팩 설정을 해주었는데요.
이렇게 설정을 해주니 이제 배포서버에서 `process.env.[환경변수]`에 접근이 가능합니다
```js
plugins: [
    new webpack.DefinePlugin({
      'process.env.API_KEY': JSON.stringify(process.env.API_KEY),
      'process.env.AUTH_DOMAIN': JSON.stringify(process.env.AUTH_DOMAIN),
      'process.env.PROJECT_ID': JSON.stringify(process.env.PROJECT_ID),
      'process.env.STORAGE_BUCKET': JSON.stringify(process.env.STORAGE_BUCKET),
      'process.env.MESSAGING_SENDER_ID': JSON.stringify(process.env.MESSAGING_SENDER_ID),
      'process.env.APP_ID': JSON.stringify(process.env.APP_ID),
      'process.env.MEASUREMENT_ID': JSON.stringify(process.env.MEASUREMENT_ID),
      'process.env.TEST': JSON.stringify(process.env.TEST),
    }),
  ],
```

`webpack.DefinePlugin`을 왜 사용하는지에 대해 검색해보니, 
> Webpack은 기본적으로 process.env.NODE_ENV 값을 제공하지 않기 때문에 사용자가 값을 등록해 사용할 수 있습니다. 
라고 합니다. 

여기서 궁금한 점이 있습니다.
1. github actions에서 정의해준 `env`는 `webpack.config.js`에서만 사용이 가능한건가요? 그렇기때문에 웹팩에서 한번더 `'process.env.API_KEY': JSON.stringify(process.env.API_KEY)` 이런식으로 작업하여 빌드된 파일에서 `process.env.[환경변수]`를 사용할 수 있게 해주는 것인가요???
